on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: prod-ui
  HELM_REPO: tochratana/gitops-fullstack

jobs:
  ci-jobs:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use with SHA
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Show the new tags value
        run: |
          echo "Tag value is: ${{ env.TAG }}"
      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin
      - name: Build Docker image and tag
        run: docker build -t ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} .
      - name: Push to Docker hub
        run: docker push ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
      - name: Logout from Dockerhub
        if: always()
        run: docker logout

  cd-jobs:
    needs: ci-jobs
    runs-on: ubuntu-latest
    environment: HELM_ENV
    steps:
      - name: Install yq command
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Add Commit SHA to TAG env
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Clone argocd repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/${{ env.HELM_REPO }}.git helm_repo
      - name: Update Helm Chart
        run: |
          cd helm_repo

          echo "Updating frontend image in full-stack-app values..."
          yq -i '.frontend.image.repository = "${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}"' charts/full-stack-app/values.yaml
          yq -i '.frontend.image.tag = "${{ env.TAG }}"' charts/full-stack-app/values.yaml

          echo "Updated values:"
          yq '.frontend.image' charts/full-stack-app/values.yaml

          git config --global user.email "${{ secrets.DOCKER_USERNAME }}@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "ci: update frontend image to ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}"
          git push
      - name: Clean up
        if: always()
        run: rm -rf helm_repo
